version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      - PORT=4200
    ports:
      - "4200:8000"

  cypress:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    command: sh -c "./run-tests-config.sh"
    depends_on:
      - app
