version: '3'
services:
  localhost:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      - PORT=4200
    ports:
      - "4200:8000"
  cypress:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    command: npx cypress open --config-file cypress.config.js
    depends_on:
      - localhost
