version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    ports:
      - "4000:80"
  cypress:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    depends_on:
      - app
