version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      - PORT=4000
    ports:
      - "4000:8000"
  cypress:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    depends_on:
      - app
