version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      - PORT=4200
    ports:
      - "4200:8000"
  cypress:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    command: cypress open --config-file cypress.config.ts
    depends_on:
      - app
    links:
      - app
