version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      - PORT=4200
    ports:
      - "4200:8000"
  cypress:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - app
    # note: inside e2e container, the network allows accessing
    # "web" host under name "web"
    # so "curl http://web" would return whatever the webserver
    # in the "web" container is cooking
    # see https://docs.docker.com/compose/networking/
    environment:
      - CYPRESS_baseUrl=http://web
    command: npx cypress run
